name: border_beam_example
description: Demo app for the border_beam package.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  border_beam_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
